version: '3.8'

services:
  product-tracker-backend:
    build: .
    container_name: product-tracker-backend
    # Hace que se se reinicie si se cae
    restart: unless-stopped
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # Límites de memoria para que no se caiga por exceder límites (ram en reposo y limite en uso)
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx160m